### ISSUE TITLE
Can this dependency be found in npm? Npm cannot found this version

### ISSUE THREAD

**Issue by elenitaex5** [AgoraIO-Extensions/agora-react-native-rtm#20]
As I use a fork of React Native Agora uikit it uses old agora-react-native-rtm from AgoraIO, but not updated from 2 years ago. I've found this, but I cannot use this dependency

**Comment by guoxianzhe** [comment]
@elenitaex5 This repo is not publish yet, we will publish it in the feature, you can use it by tag:

`npm install AgoraIO-Extensions/agora-react-native-rtm@2.1.12
`
